/*
 *   Copyright 2007 skynamics AG
 *
 *   Licensed under the Apache License, Version 2.0 (the "License");
 *   you may not use this file except in compliance with the License.
 *   You may obtain a copy of the License at
 *
 *       http://www.apache.org/licenses/LICENSE-2.0
 *
 *   Unless required by applicable law or agreed to in writing, software
 *   distributed under the License is distributed on an "AS IS" BASIS,
 *   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *   See the License for the specific language governing permissions and
 *   limitations under the License.
 */
package org.openbp.server.engine;

import org.openbp.core.engine.EngineException;

/**
 * Exception that is generated by an engine trace client (debugger or profiler)
 * in order to abort a running process.
 *
 * @author Heiko Erhardt
 */
public class EngineTraceException extends EngineException
{
	/**
	 * Constructor.
	 * @param msg Exception message
	 */
	public EngineTraceException(String msg)
	{
		super("DebugAbort", msg);
	}
}
