CREATE TABLE OPENBPTOKENCONTEXT (
    TC_ID VARCHAR(40) NOT NULL,
    TC_VERSION BIGINT NOT NULL,
    TC_LIFECYCLE_STATE BIGINT,
    TC_LIFECYCLE_REQUEST BIGINT,
    TC_EXECUTING_MODEL VARCHAR(250),
    TC_CURRENT_SOCKET VARCHAR(250),
    TC_QUEUE_TYPE VARCHAR(50),
    TC_USER_ID VARCHAR(50),
    TC_DEBUGGER_ID VARCHAR(20),
    TC_NODE_ID VARCHAR(100),
    TC_PRIORITY BIGINT,
    TC_PROGRESS_COUNT BIGINT,
    TC_PROGRESS_TOTAL BIGINT,
    TC_PROGRESS_TEXT VARCHAR(250),
    TC_DATA BLOB(2G) NOT LOGGED,
    TC_PARENT_ID VARCHAR(40),
    CONSTRAINT TC_PK PRIMARY KEY(TC_ID)
)!

CREATE TABLE OPENBPWORKFLOWTASK (
    TASK_ID VARCHAR(40) NOT NULL,
    TASK_VERSION BIGINT NOT NULL,
    TASK_NAME VARCHAR(40),
    TASK_DISPLAY_NAME VARCHAR(200),
    TASK_DESCRIPTION VARCHAR(255),
    TASK_STEP_NAME VARCHAR(40),
    TASK_STEP_DISPLAYNAME VARCHAR(200),
    TASK_STEP_DESCRIPTION VARCHAR(255),
    TASK_ROLE_ID VARCHAR(40),
    TASK_USER_ID VARCHAR(40),
    TASK_PERMISSIONS VARCHAR(255),
    TASK_TIME_CREATED TIMESTAMP,
    TASK_TIME_ACCEPTED TIMESTAMP,
    TASK_TIME_COMPLETED TIMESTAMP,
    TASK_CREATING_USER_ID VARCHAR(40),
    TASK_ACCEPTING_USER_ID VARCHAR(40),
    TASK_PRIORITY BIGINT,
    TASK_DUE_TIME TIMESTAMP,
    TASK_STATUS BIGINT,
    TASK_DELETE_AFTER_COMPLETION INTEGER,
    TASK_CONTEXT_ID VARCHAR(40) NOT NULL,
    CONSTRAINT TASK_PK PRIMARY KEY(TASK_ID)
)!

CREATE INDEX TC_PARENT_FK
    ON OPENBPTOKENCONTEXT(TC_PARENT_ID)!

CREATE INDEX TC_PRIORITY_IND
	ON OPENBPTOKENCONTEXT(TC_PRIORITY)!

ALTER TABLE OPENBPTOKENCONTEXT
	ADD CONSTRAINT TC_PARENT_FK
	FOREIGN KEY(TC_PARENT_ID)
	REFERENCES OPENBPTOKENCONTEXT(TC_ID)!

ALTER TABLE OPENBPWORKFLOWTASK
	ADD CONSTRAINT TASK_TC_FK
	FOREIGN KEY(TASK_CONTEXT_ID)
	REFERENCES OPENBPTOKENCONTEXT(TC_ID)!
