CREATE TABLE ABSENCEDATA (
	ABS_ID INTEGER NOT NULL,
	ABS_SUBMITTER_NAME VARCHAR(40),
	ABS_SUBMITTER_EMAIL VARCHAR(40),
	ABS_STATE INTEGER,
	ABS_REASON VARCHAR(40),
	ABS_FROM_DATE DATE,
	ABS_TO_DATE DATE,
	PRIMARY KEY (PCP_ID)
);
