CREATE TABLE OPENBPTOKENCONTEXT (
	TC_ID VARCHAR(40) NOT NULL,
	TC_VERSION INTEGER NOT NULL,
	TC_LIFECYCLE_STATE INTEGER,
	TC_LIFECYCLE_REQUEST INTEGER,
	TC_EXECUTING_MODEL VARCHAR(250),
	TC_CURRENT_SOCKET VARCHAR(250),
	TC_QUEUE_TYPE VARCHAR(50),
	TC_USER_ID VARCHAR(40),
	TC_DEBUGGER_ID VARCHAR(20),
	TC_NODE_ID VARCHAR(100),
	TC_PRIORITY INTEGER,
	TC_PROGRESS_COUNT INTEGER,
	TC_PROGRESS_TOTAL INTEGER,
	TC_PROGRESS_TEXT VARCHAR(250),
	TC_DATA LONG VARCHAR FOR BIT DATA,
	TC_PARENT_ID VARCHAR(40),
	PRIMARY KEY (TC_ID)
);

CREATE TABLE OPENBPWORKFLOWTASK (
	TASK_ID VARCHAR(40) NOT NULL,
	TASK_VERSION INTEGER NOT NULL,
	TASK_NAME VARCHAR(40),
	TASK_DISPLAY_NAME VARCHAR(200),
	TASK_DESCRIPTION VARCHAR(255),
	TASK_STEP_NAME VARCHAR(40),
	TASK_STEP_DISPLAYNAME VARCHAR(200),
	TASK_STEP_DESCRIPTION VARCHAR(255),
	TASK_ROLE_ID VARCHAR(40),
	TASK_USER_ID VARCHAR(40),
	TASK_PERMISSIONS VARCHAR(255),
	TASK_TIME_CREATED TIMESTAMP,
	TASK_TIME_ACCEPTED TIMESTAMP,
	TASK_TIME_COMPLETED TIMESTAMP,
	TASK_CREATING_USER_ID VARCHAR(40),
	TASK_ACCEPTING_USER_ID VARCHAR(40),
	TASK_PRIORITY INTEGER,
	TASK_DUE_TIME TIMESTAMP,
	TASK_STATUS INTEGER,
	TASK_DELETE_AFTER_COMPLETION SMALLINT,
	TASK_CONTEXT_ID VARCHAR(40) NOT NULL,
	PRIMARY KEY (TASK_ID)
);

CREATE INDEX FK_OPENBPTOKENCONTEXT_PARENT_ID ON OPENBPTOKENCONTEXT(TC_PARENT_ID);

ALTER TABLE OPENBPTOKENCONTEXT 
	ADD CONSTRAINT FK_OPENBPTOKENCONTEXT_PARENT_ID
	FOREIGN KEY (TC_PARENT_ID) 
	REFERENCES OPENBPTOKENCONTEXT (TC_ID);

CREATE INDEX FK_OPENBPTOKENCONTEXT_PRIORITY ON OPENBPTOKENCONTEXT (TC_PRIORITY);

CREATE INDEX FK_OPENBPWORKFLOWTASK_CONTEXT_ID ON OPENBPWORKFLOWTASK(TASK_CONTEXT_ID);

ALTER TABLE OPENBPWORKFLOWTASK 
	ADD CONSTRAINT FK_OPENBPWORKFLOWTASK_CONTEXT_ID 
	FOREIGN KEY (TASK_CONTEXT_ID)
	REFERENCES OPENBPTOKENCONTEXT (TC_ID);


CREATE TABLE OPENBPMODELITEM (
	MI_ID VARCHAR(40) NOT NULL,
	MI_VERSION INTEGER NOT NULL,
	MI_MODEL_NAME VARCHAR(250),
	MI_ITEM_NAME VARCHAR(250),
	MI_ITEM_TYPE VARCHAR(10),
	MI_XML CLOB(50000),
	PRIMARY KEY (MI_ID)
);

CREATE TABLE OPENBPMODEL (
	MO_ID VARCHAR(40) NOT NULL,
	MO_VERSION INTEGER NOT NULL,
	MO_NAME VARCHAR(250),
	MO_XML CLOB(50000),
	PRIMARY KEY (MO_ID)
);

CREATE INDEX FK_OPENBPMODEL_NAME ON OPENBPMODEL(MO_NAME);
CREATE INDEX FK_OPENBPMODELITEM_MODEL_NAME ON OPENBPMODELITEM(MI_MODEL_NAME);
