ALTER TABLE OPENBPWORKFLOWTASK DROP FOREIGN KEY FK_OPENBPWORKFLOWTASK_CONTEXT_ID;
ALTER TABLE OPENBPTOKENCONTEXT DROP FOREIGN KEY FK_OPENBPTOKENCONTEXT_PARENT_ID;
DROP TABLE IF EXISTS OPENBPWORKFLOWTASK;
DROP TABLE IF EXISTS OPENBPTOKENCONTEXT;
