CREATE TABLE ABSENCEDATA (
	AD_ID INTEGER NOT NULL,
	SUBMITTER_NAME VARCHAR(40),
	SUBMITTER_EMAIL VARCHAR(40),
	STATE INTEGER,
	REASON VARCHAR(40),
	FROM_DATE DATE,
	TO_DATE VARCHAR(40),
	PRIMARY KEY (PCP_ID)
);
